### ISSUE TITLE
Use `schema:` instead of `schema-org:` prefix

### ISSUE THREAD

**Issue by BigBlueHat** [aml-org/examples#1]
First, amazing work, and thank you for building this project and sharing it!

Second, a wee nit pick about the prefixes. This isn't a huge deal because (obviously) the `@context` handles the mapping, but there is a prevailing pattern--thanks to the [RDFa initial context](https://www.w3.org/2011/rdfa-context/rdfa-1.1) to use `schema:` as the preferred prefix for http://schema.org/ terms.

Might be worth changing that, so it feels more familiar with other projects--and you get the bonus for folks searching for `schema:name` and such.

Cheers!
🎩

**Comment by tomsfernandez** [comment]
Hi @BigBlueHat! First of all sorry that we didn't see this issue back in 2019, it is a big miss from our part. At the time we weren't checking Github issues as we do now.

Thanks for the comments! Some time between this issues' creation and now we stopped using the `http://schema.org` uri so the feedback isn't applicable know but it would have been awesome to apply it back then.

I'm closing this as it isn't applicable know. Stay safe!
