### ISSUE TITLE
Maven packaging for tests

### ISSUE THREAD

**Issue by jgsuess** [aml-org/examples#56]
I am bundling AMF for use in OSGI and having issues keeping tests in sync. Is there any chance these files could be provided via Maven?

**Comment by tomsfernandez** [comment]
Hi @jgsuess. Sorry for answering a month later, we weren't expecting Github Issues being created in this repository (we didn't have any automatic notifications).

We won't be packaging and provisioning this via Maven as it implies creating and maintaining another artifact and we won't have the manpower to do that. Besides, the code in this repository is only intended for documentation purposes, not as part of our test suite.

If you really want it you could probably automate it by forking this repository and with Github Actions, pull the codebase once a day and publishing that artifact into the Github Package Registry or the one you like.
